name: CI

permissions:
  contents: read
  id-token: write

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun run lint
      - run: bun run format
      - run: bun run bundle
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            dist
            package.json
            readme.md
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/download-artifact@v4
        with: { name: build-artifact }
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Clean package.json for publishing
        run: |
          npm pkg delete scripts
          npm pkg delete dependencies
          npm pkg delete devDependencies
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            npm publish --tag latest --access public --provenance
          else
            npm publish --tag next   --access public --provenance
          fi